# Generated by Django 4.2.30 on 2026-06-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0007_membership_work_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("break_duration_minutes", models.PositiveIntegerField(default=60)),
                ("is_night_shift", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, default="")),
                ("annual_quota", models.PositiveIntegerField(default=0)),
                ("is_paid", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True)),
                ("allow_half_day", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_types",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_days", models.DecimalField(decimal_places=1, max_digits=5)),
                ("is_half_day", models.BooleanField(default=False)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_requests",
                        to="companies.membership",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="companies.company",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests",
                        to="attendance.leavetype",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="companies.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("state", "State"),
                            ("company", "Company"),
                            ("optional", "Optional"),
                        ],
                        default="company",
                        max_length=30,
                    ),
                ),
                ("holiday_date", models.DateField()),
                ("description", models.TextField(blank=True, default="")),
                ("is_paid", models.BooleanField(default=True)),
                ("is_half_day", models.BooleanField(default=False)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["holiday_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_shifts",
                        to="companies.membership",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to="companies.membership",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assignments",
                        to="attendance.shift",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="CompanyWorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("working_days", models.JSONField(default=list)),
                ("weekend_days", models.JSONField(default=list)),
                ("work_start_time", models.TimeField()),
                ("work_end_time", models.TimeField()),
                ("break_minutes", models.PositiveIntegerField(default=60)),
                ("timezone", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("holiday_sync_enabled", models.BooleanField(default=False)),
                (
                    "holiday_provider",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedule",
                        to="companies.company",
                    ),
                ),
                (
                    "default_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_work_schedules",
                        to="attendance.shift",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attendance_date", models.DateField()),
                ("check_in_at", models.DateTimeField(blank=True, null=True)),
                ("check_out_at", models.DateTimeField(blank=True, null=True)),
                ("total_work_minutes", models.PositiveIntegerField(default=0)),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("early_exit_minutes", models.PositiveIntegerField(default=0)),
                ("overtime_minutes", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("on_leave", "On Leave"),
                            ("holiday", "Holiday"),
                            ("weekend", "Weekend"),
                        ],
                        default="absent",
                        max_length=30,
                    ),
                ),
                ("is_regularized", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="companies.company",
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="attendance.leaverequest",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="companies.membership",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="attendance.shift",
                    ),
                ),
            ],
            options={
                "ordering": ["-attendance_date"],
            },
        ),
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("required_work_minutes", models.PositiveIntegerField(default=480)),
                ("half_day_below_minutes", models.PositiveIntegerField(default=240)),
                ("late_after_minutes", models.PositiveIntegerField(default=10)),
                ("early_exit_before_minutes", models.PositiveIntegerField(default=30)),
                ("overtime_enabled", models.BooleanField(default=False)),
                ("overtime_after_minutes", models.PositiveIntegerField(default=480)),
                ("auto_absent_if_no_checkin", models.BooleanField(default=True)),
                ("count_weekend_as_overtime", models.BooleanField(default=False)),
                (
                    "attendance_regularization_enabled",
                    models.BooleanField(default=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_policy",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["company"], name="attendance__company_33495a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["is_active"], name="attendance__is_acti_3b5f01_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("company", "name")},
        ),
        migrations.AddIndex(
            model_name="leavetype",
            index=models.Index(
                fields=["company"], name="attendance__company_5143c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leavetype",
            index=models.Index(
                fields=["is_active"], name="attendance__is_acti_61b8cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavetype",
            unique_together={("company", "code")},
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["company"], name="attendance__company_0f15d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["membership"], name="attendance__members_d91dc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["status"], name="attendance__status_6e3dfd_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date"], name="attendance__start_d_89764a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["company"], name="attendance__company_e63dd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["holiday_date"], name="attendance__holiday_81af93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["holiday_type"], name="attendance__holiday_e0514a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("company", "holiday_date", "name")},
        ),
        migrations.AddIndex(
            model_name="employeeshiftassignment",
            index=models.Index(
                fields=["membership"], name="attendance__members_b41d88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeshiftassignment",
            index=models.Index(fields=["shift"], name="attendance__shift_i_9f9415_idx"),
        ),
        migrations.AddIndex(
            model_name="employeeshiftassignment",
            index=models.Index(
                fields=["effective_from"], name="attendance__effecti_1bc03a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeshiftassignment",
            index=models.Index(
                fields=["is_active"], name="attendance__is_acti_99b2eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyworkschedule",
            index=models.Index(
                fields=["company"], name="attendance__company_b33cca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyworkschedule",
            index=models.Index(
                fields=["country"], name="attendance__country_ef4ac1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyworkschedule",
            index=models.Index(
                fields=["default_shift"], name="attendance__default_4ca440_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyworkschedule",
            index=models.Index(
                fields=["is_active"], name="attendance__is_acti_ca7344_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["company"], name="attendance__company_52485d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["membership"], name="attendance__members_e61a4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["attendance_date"], name="attendance__attenda_ee6011_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["status"], name="attendance__status_741eb8_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["company", "attendance_date"],
                name="attendance__company_6fc6c8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("membership", "attendance_date")},
        ),
        migrations.AddIndex(
            model_name="attendancepolicy",
            index=models.Index(
                fields=["is_active"], name="attendance__is_acti_68efdf_idx"
            ),
        ),
    ]
