# Generated by Django 4.2.30 on 2026-06-18 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_membership_work_mode_and_more"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceAccessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Rule Name")),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("WORK_MODE", "Work Mode Scope"),
                            ("DEPARTMENT", "Department Scope"),
                        ],
                        max_length=20,
                        verbose_name="Scope Type",
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("office", "Office"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("field", "Field"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="Target Work Mode",
                    ),
                ),
                (
                    "validation_mode",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary Method Only"),
                            ("ALL", "All Configured Methods Required"),
                            ("ANY", "Any Configured Method Allowed"),
                        ],
                        default="ANY",
                        max_length=15,
                        verbose_name="Validation Mode",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Evaluation Priority"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Attendance Access Rule",
                "verbose_name_plural": "Attendance Access Rules",
                "db_table": "attendance_access_rules",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CHECK_IN", "Clock In Event"),
                            ("CHECK_OUT", "Clock Out Event"),
                            ("BREAK_OUT", "Begin Break Intermission"),
                            ("BREAK_IN", "Return From Break Intermission"),
                        ],
                        max_length=20,
                        verbose_name="Workflow Event Action Action Type",
                    ),
                ),
                (
                    "attendance_method",
                    models.CharField(
                        choices=[
                            ("GPS_FACE", "Combined Geofence & Facial Matching"),
                            ("GPS_ONLY", "Geofence Verification Only"),
                            ("FACE_ONLY", "Facial Identification Portal Only"),
                            ("BIOMETRIC", "Hardware Fingerprint Terminal Interface"),
                            ("MANUAL", "HR Administrative Overwrite Adjustment"),
                        ],
                        max_length=20,
                        verbose_name="Verification Pathway Channel Used",
                    ),
                ),
                (
                    "event_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Timezone Aware Punch Time Timestamp UTC",
                    ),
                ),
                (
                    "verification_payload",
                    models.JSONField(
                        default=dict,
                        verbose_name="Ingestion Metadata Evidence Payload Snapshot File",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Administrative Narrative Notes Text",
                    ),
                ),
                (
                    "is_system_generated",
                    models.BooleanField(
                        default=False,
                        verbose_name="Automated Machine Event Trigger Flag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Workflow Action Event",
                "verbose_name_plural": "Attendance Workflow Action Events",
                "db_table": "attendance_events",
                "ordering": ["-event_time"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Location Label Name"
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Human Readable Address Description",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="Target Latitude Coordinate",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="Target Longitude Coordinate",
                    ),
                ),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=150, verbose_name="Geofence Radius Threshold Bounds"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Determines if employees are evaluated against this boundary.",
                        verbose_name="Operational Verification Flag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Location Perimeter",
                "verbose_name_plural": "Attendance Location Perimeters",
                "db_table": "attendance_locations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BiometricDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Device Display Name"
                    ),
                ),
                (
                    "device_code",
                    models.CharField(
                        max_length=50, verbose_name="Human Readable Device Identifier"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("ZKTECO", "ZKTEco"),
                            ("ESSL", "eSSL"),
                            ("SUPREMA", "Suprema"),
                            ("HIKVISION", "Hikvision"),
                            ("MATRIX", "Matrix"),
                            ("OTHER", "Other/Generic Vendor"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Hardware Vendor Brand",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Vendor Model Specification Number",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Required for hardware deployed under direct PULL-based synchronization frameworks.",
                        null=True,
                        verbose_name="Network IP Address",
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        default=4370, verbose_name="Communication Network Port"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Hardware Factory Serial Number",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Kolkata",
                        max_length=100,
                        verbose_name="Device Local Operating Timezone",
                    ),
                ),
                (
                    "sync_mode",
                    models.CharField(
                        choices=[
                            ("PULL", "HRMS Fetches Logs (Scheduled Pull)"),
                            ("PUSH", "Device Pushes Logs (Real-time HTTP/Cloud)"),
                            ("MANUAL", "Administrative Manual File Import"),
                        ],
                        default="MANUAL",
                        max_length=15,
                        verbose_name="Synchronization Architecture Interface Mode",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivating blocks background log synchronization while maintaining transaction history lines.",
                        verbose_name="Operational Tracking Status Flag",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Last Successful Sync Timeline Mark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Device Terminal",
                "verbose_name_plural": "Biometric Device Terminals",
                "db_table": "attendance_biometric_devices",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BiometricEmployeeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_user_id",
                    models.CharField(
                        max_length=100,
                        verbose_name="Hardware Internal Device User ID Index",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disabling ignores streaming clock log hashes associated with this pairing string context.",
                        verbose_name="Active Processing State Flag",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="System Registration Ingestion Timestamp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Employee Identity Mapping",
                "verbose_name_plural": "Biometric Employee Identity Mappings",
                "db_table": "attendance_biometric_employee_mappings",
                "ordering": ["membership"],
            },
        ),
        migrations.CreateModel(
            name="BiometricLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_user_id",
                    models.CharField(
                        max_length=100,
                        verbose_name="Hardware Internal Device Identity Pointer Tag",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CHECK_IN", "Clock In Punch Event"),
                            ("CHECK_OUT", "Clock Out Punch Event"),
                            ("BREAK_OUT", "Break Out Intermission Event"),
                            ("BREAK_IN", "Break In Return Event"),
                            ("UNKNOWN", "Unclassified Ingestion Pulse"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                        verbose_name="Calculated Raw Event Mode Action",
                    ),
                ),
                (
                    "punch_time",
                    models.DateTimeField(
                        verbose_name="Timezone Aware Ingestion UTC Timestamp Execution"
                    ),
                ),
                (
                    "device_log_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Hardware Unique Vendor Transaction Instance ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PULL", "Pull"),
                            ("PUSH", "Push"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=15,
                        verbose_name="Ingestion Transmission Vector Route",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        default=dict,
                        verbose_name="Immutable Context Metadata Footprint Payload Snapshot",
                    ),
                ),
                (
                    "sync_batch_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Execution Orchestration Pipeline Sync Batch Index Identifier",
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Awaiting Calculation Engine Evaluation"),
                            (
                                "PROCESSED",
                                "Successfully Parsed Into Dynamic Shift Records",
                            ),
                            ("FAILED", "Processing Exception Blocked Execution"),
                            ("IGNORED", "De-duplicated/Omitted from Calculations"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="State Status Management Engine Node",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Consumption Timestamp Execution Mark",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Processing Failure Error Diagnostic Log Out",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Raw Device Punch Log",
                "verbose_name_plural": "Biometric Raw Device Punch Logs",
                "db_table": "attendance_biometric_logs",
                "ordering": ["-punch_time"],
            },
        ),
        migrations.CreateModel(
            name="CompanyAttendanceDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "validation_mode",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary Method Only"),
                            ("ALL", "All Configured Methods Required"),
                            ("ANY", "Any Configured Method Allowed"),
                        ],
                        default="ANY",
                        max_length=15,
                        verbose_name="Validation Mode",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Company Attendance Default",
                "verbose_name_plural": "Company Attendance Defaults",
                "db_table": "attendance_company_defaults",
            },
        ),
        migrations.CreateModel(
            name="CompanyAttendanceMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("WEB", "Web/Mobile Dashboard Portal"),
                            ("GPS", "Geofenced Coordinate Boundary"),
                            ("FACE", "Biometric Facial Recognition Engine"),
                            ("BIOMETRIC", "Hardware Fingerprint Terminal"),
                            ("MANUAL", "Administrative Manual Overwrite"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Ingestion Channel Method Interface",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Toggles validation availability without executing destructive record purges.",
                        verbose_name="Operational Verification Flag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Attendance Method Configuration",
                "verbose_name_plural": "Company Attendance Method Configurations",
                "db_table": "attendance_company_methods",
                "ordering": ["method"],
            },
        ),
        migrations.CreateModel(
            name="CompanyFaceEnrollmentPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            (
                                "SELF_ONLY",
                                "Employee Self Enrollment Only (Auto-Approve)",
                            ),
                            ("HR_ONLY", "HR Restricted Enrollment Only"),
                            (
                                "SELF_WITH_APPROVAL",
                                "Employee Self Enrollment with HR Approval Required",
                            ),
                        ],
                        default="SELF_WITH_APPROVAL",
                        max_length=30,
                        verbose_name="Biometric Policy Strategy Type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Operational Verification Flag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Face Enrollment Policy",
                "verbose_name_plural": "Company Face Enrollment Policies",
                "db_table": "attendance_company_face_policies",
            },
        ),
        migrations.CreateModel(
            name="DailyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_date",
                    models.DateField(
                        db_index=True, verbose_name="Operational Tracking Target Date"
                    ),
                ),
                (
                    "schedule_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Captures work hours and shift structures active on tracking runtime context.",
                        verbose_name="Frozen Operating Schedule Specifications",
                    ),
                ),
                (
                    "policy_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Captures thresholds for lateness grace scales, half-day cuts, and overtime activation.",
                        verbose_name="Frozen Administrative Governance Rules",
                    ),
                ),
                (
                    "first_check_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="First Clock In Log"
                    ),
                ),
                (
                    "last_check_out_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Clock Out Log"
                    ),
                ),
                (
                    "total_work_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Net Active Work Minutes"
                    ),
                ),
                (
                    "total_break_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Net Active Break Minutes"
                    ),
                ),
                (
                    "required_work_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Mandatory Target Output Minutes"
                    ),
                ),
                (
                    "overtime_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Validated Overtime Minutes"
                    ),
                ),
                (
                    "late_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Lateness Accumulation Minutes"
                    ),
                ),
                (
                    "early_exit_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Early Exit Departure Variance Minutes"
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("HALF_DAY", "Half Day"),
                            ("LEAVE", "On Approved Leave"),
                            ("HOLIDAY", "Company Observed Holiday"),
                            ("WEEKEND", "Scheduled Weekend Rest Day"),
                            ("INCOMPLETE", "Incomplete Tracking Sequence"),
                            ("REVIEW_REQUIRED", "HR Administrative Review Required"),
                        ],
                        default="ABSENT",
                        max_length=20,
                        verbose_name="Daily Synthesis Calculation Status",
                    ),
                ),
                ("is_present", models.BooleanField(default=False)),
                ("is_half_day", models.BooleanField(default=False)),
                ("is_absent", models.BooleanField(default=True)),
                ("is_late", models.BooleanField(default=False)),
                ("is_early_exit", models.BooleanField(default=False)),
                ("is_holiday", models.BooleanField(default=False)),
                ("is_weekend", models.BooleanField(default=False)),
                ("is_leave", models.BooleanField(default=False)),
                (
                    "is_auto_closed",
                    models.BooleanField(
                        default=False, verbose_name="Machine Automated Closure Flag"
                    ),
                ),
                (
                    "auto_close_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Auto-checkout Narrative Summary",
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False, verbose_name="HR Attention Exception Alert Flag"
                    ),
                ),
                (
                    "review_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="HR Evaluation Diagnostic Log Out",
                    ),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Payroll Freezing Timestamp"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ENGINE", "Automated Processing Pipeline Engine"),
                            ("MANUAL", "Explicit HR Administrator Overwrite"),
                            ("REPROCESSED", "Historical Recalculation Synchronization"),
                        ],
                        default="ENGINE",
                        max_length=20,
                        verbose_name="Processing Operation Flow Provenance Origin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Attendance Ledger Summary Record",
                "verbose_name_plural": "Daily Attendance Ledger Summary Records",
                "db_table": "attendance_daily_summary_ledger",
                "ordering": ["-attendance_date", "membership"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeAttendanceOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "validation_mode",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary Method Only"),
                            ("ALL", "All Configured Methods Required"),
                            ("ANY", "Any Configured Method Allowed"),
                        ],
                        default="ANY",
                        max_length=15,
                        verbose_name="Validation Mode",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Reason for Override"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Employee Attendance Override",
                "verbose_name_plural": "Employee Attendance Overrides",
                "db_table": "attendance_employee_overrides",
            },
        ),
        migrations.CreateModel(
            name="FaceEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Awaiting HR Verification Review"),
                            (
                                "APPROVED",
                                "Active and Allowed for Verification Sign-ins",
                            ),
                            ("REJECTED", "Enrollment Denied by Administrator"),
                            (
                                "REVOKED",
                                "Previously Active Profile Explicitly Deactivated",
                            ),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                        verbose_name="Verification Status State",
                    ),
                ),
                (
                    "enrollment_source",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee Self Service Registration"),
                            ("HR", "HR Administrator Initiated Assignment"),
                        ],
                        max_length=15,
                        verbose_name="Enrollment Registration Origin",
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        help_text="Stores mathematical float structures capturing biometric attributes. Image data is discarded.",
                        verbose_name="Math Matrix Feature Vector Embeddings Array Hash",
                    ),
                ),
                (
                    "embedding_version",
                    models.CharField(
                        default="v1.0.0",
                        max_length=50,
                        verbose_name="Model Architecture Ingestion Version Name",
                    ),
                ),
                (
                    "similarity_threshold",
                    models.FloatField(
                        default=0.85,
                        verbose_name="Minimum Cosine Passing Vector Confidence Limit",
                    ),
                ),
                (
                    "liveness_verified",
                    models.BooleanField(
                        default=False,
                        verbose_name="Anti-Spoofing Liveness Verification Status Check Passed",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Approval Execution Timestamp",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Administrative Rejection Narrative Explanation",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Revocation Execution Timestamp",
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Administrative Revocation Narrative Explanation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Face Profile Enrollment",
                "verbose_name_plural": "Biometric Face Profile Enrollments",
                "db_table": "attendance_face_enrollments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attendance__company_52485d_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attendance__members_e61a4d_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attendance__attenda_ee6011_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attendance__status_741eb8_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attendance__company_6fc6c8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="faceenrollment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_face_enrollments",
                to="companies.membership",
                verbose_name="Approving Administrator Context",
            ),
        ),
        migrations.AddField(
            model_name="faceenrollment",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="face_enrollments",
                to="companies.company",
                verbose_name="Company Context",
            ),
        ),
        migrations.AddField(
            model_name="faceenrollment",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="face_enrollments",
                to="companies.membership",
                verbose_name="Employee Profile Context",
            ),
        ),
        migrations.AddField(
            model_name="faceenrollment",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_face_enrollments",
                to="companies.membership",
                verbose_name="Revoking Administrator Context",
            ),
        ),
        migrations.AddField(
            model_name="employeeattendanceoverride",
            name="allowed_locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="employee_overrides",
                to="attendance.attendancelocation",
                verbose_name="Allowed Locations",
            ),
        ),
        migrations.AddField(
            model_name="employeeattendanceoverride",
            name="allowed_methods",
            field=models.ManyToManyField(
                related_name="employee_overrides",
                to="attendance.companyattendancemethod",
                verbose_name="Allowed Methods",
            ),
        ),
        migrations.AddField(
            model_name="employeeattendanceoverride",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_attendance_overrides",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="employeeattendanceoverride",
            name="membership",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_override",
                to="companies.membership",
                verbose_name="Employee Membership",
            ),
        ),
        migrations.AddField(
            model_name="dailyattendance",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_attendance_records",
                to="companies.company",
                verbose_name="Company Context Scope",
            ),
        ),
        migrations.AddField(
            model_name="dailyattendance",
            name="finalized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finalized_daily_attendance_sheets",
                to="companies.membership",
                verbose_name="Freezing Auditor Profile Context",
            ),
        ),
        migrations.AddField(
            model_name="dailyattendance",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_attendance_records",
                to="companies.membership",
                verbose_name="Employee Profile Reference Context",
            ),
        ),
        migrations.AddField(
            model_name="companyfaceenrollmentpolicy",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="face_enrollment_policy",
                to="companies.company",
                verbose_name="Company Workspace Scope",
            ),
        ),
        migrations.AddField(
            model_name="companyattendancemethod",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_methods",
                to="companies.company",
                verbose_name="Company Workspace Context",
            ),
        ),
        migrations.AddField(
            model_name="companyattendancemethod",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configured_attendance_methods",
                to="companies.membership",
                verbose_name="Audit Trail Instigator",
            ),
        ),
        migrations.AddField(
            model_name="companyattendancedefault",
            name="allowed_locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_configurations",
                to="attendance.attendancelocation",
                verbose_name="Allowed Locations",
            ),
        ),
        migrations.AddField(
            model_name="companyattendancedefault",
            name="allowed_methods",
            field=models.ManyToManyField(
                related_name="default_configurations",
                to="attendance.companyattendancemethod",
                verbose_name="Allowed Methods",
            ),
        ),
        migrations.AddField(
            model_name="companyattendancedefault",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_default",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="biometriclog",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometric_logs",
                to="companies.company",
                verbose_name="Company Context Scope Target",
            ),
        ),
        migrations.AddField(
            model_name="biometriclog",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biometric_logs",
                to="attendance.biometricdevice",
                verbose_name="Originating Device Configuration",
            ),
        ),
        migrations.AddField(
            model_name="biometriclog",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biometric_logs",
                to="companies.membership",
                verbose_name="Resolved Employee Identity Profile Map Context",
            ),
        ),
        migrations.AddField(
            model_name="biometricemployeemapping",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometric_employee_mappings",
                to="companies.company",
                verbose_name="Company Context Dashboard Scope",
            ),
        ),
        migrations.AddField(
            model_name="biometricemployeemapping",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_biometric_mappings",
                to="companies.membership",
                verbose_name="Audit Trail Instigator Reference Context",
            ),
        ),
        migrations.AddField(
            model_name="biometricemployeemapping",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_mappings",
                to="attendance.biometricdevice",
                verbose_name="Assigned Biometric Device Terminal Target",
            ),
        ),
        migrations.AddField(
            model_name="biometricemployeemapping",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometric_mappings",
                to="companies.membership",
                verbose_name="Employee Profile Context Reference",
            ),
        ),
        migrations.AddField(
            model_name="biometricdevice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometric_devices",
                to="companies.company",
                verbose_name="Company Context",
            ),
        ),
        migrations.AddField(
            model_name="attendancelocation",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_locations",
                to="companies.company",
                verbose_name="Company Workspace Context",
            ),
        ),
        migrations.AddField(
            model_name="attendancelocation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_attendance_locations",
                to="companies.membership",
                verbose_name="Audit Trail Instigator",
            ),
        ),
        migrations.AddField(
            model_name="attendanceevent",
            name="biometric_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_events",
                to="attendance.biometriclog",
                verbose_name="Linked Streaming Raw Hardware Log Sync Record",
            ),
        ),
        migrations.AddField(
            model_name="attendanceevent",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_events",
                to="companies.company",
                verbose_name="Company Context Scope Target",
            ),
        ),
        migrations.AddField(
            model_name="attendanceevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instigated_attendance_events",
                to="companies.membership",
                verbose_name="Action Trail Instigator Profile Context",
            ),
        ),
        migrations.AddField(
            model_name="attendanceevent",
            name="face_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_events",
                to="attendance.faceenrollment",
                verbose_name="Matched Biometric Face Enrollment Signature",
            ),
        ),
        migrations.AddField(
            model_name="attendanceevent",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_events",
                to="attendance.attendancelocation",
                verbose_name="Matched Geofence Perimeter Point Location",
            ),
        ),
        migrations.AddField(
            model_name="attendanceevent",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_events",
                to="companies.membership",
                verbose_name="Employee Profile Target",
            ),
        ),
        migrations.AddField(
            model_name="attendanceaccessrule",
            name="allowed_locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="access_rules",
                to="attendance.attendancelocation",
                verbose_name="Allowed Locations",
            ),
        ),
        migrations.AddField(
            model_name="attendanceaccessrule",
            name="allowed_methods",
            field=models.ManyToManyField(
                related_name="access_rules",
                to="attendance.companyattendancemethod",
                verbose_name="Allowed Methods",
            ),
        ),
        migrations.AddField(
            model_name="attendanceaccessrule",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_access_rules",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="attendanceaccessrule",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_access_rules",
                to="companies.department",
                verbose_name="Target Department",
            ),
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="attendance_date",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="check_in_at",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="check_out_at",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="company",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="early_exit_minutes",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="is_regularized",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="late_minutes",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="leave_request",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="membership",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="overtime_minutes",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="shift",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="status",
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="total_work_minutes",
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["company", "attendance_date"], name="daily_att_company_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["company", "membership"], name="daily_att_company_member_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["company", "attendance_status"],
                name="daily_att_company_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["company", "finalized_at"], name="daily_att_finalized_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["company", "attendance_date", "attendance_status"],
                name="daily_att_date_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyattendance",
            constraint=models.UniqueConstraint(
                fields=("company", "membership", "attendance_date"),
                name="unique_daily_attendance_summary_per_employee_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyattendancemethod",
            constraint=models.UniqueConstraint(
                fields=("company", "method"),
                name="unique_company_attendance_method_interface",
            ),
        ),
        migrations.AddIndex(
            model_name="biometriclog",
            index=models.Index(
                fields=["company", "punch_time"], name="biom_log_company_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometriclog",
            index=models.Index(
                fields=["company", "processing_status"], name="biom_log_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometriclog",
            index=models.Index(
                fields=["company", "device"], name="biom_log_device_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometriclog",
            index=models.Index(
                fields=["company", "membership"], name="biom_log_member_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometriclog",
            index=models.Index(
                fields=["company", "source"], name="biom_log_source_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="biometriclog",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("device_log_id__isnull", False), ("device__isnull", False)
                ),
                fields=("company", "device", "device_log_id"),
                name="unique_vendor_log_transaction_per_device_perimeter",
            ),
        ),
        migrations.AddIndex(
            model_name="biometricemployeemapping",
            index=models.Index(
                fields=["company", "membership"], name="biom_map_member_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricemployeemapping",
            index=models.Index(
                fields=["company", "device"], name="biom_map_device_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricemployeemapping",
            index=models.Index(
                fields=["company", "is_active"], name="biom_map_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="biometricemployeemapping",
            constraint=models.UniqueConstraint(
                fields=("company", "device", "device_user_id"),
                name="unique_device_user_identity_per_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="biometricemployeemapping",
            constraint=models.UniqueConstraint(
                fields=("company", "membership", "device"),
                name="unique_employee_device_pairing_per_company",
            ),
        ),
        migrations.AddIndex(
            model_name="biometricdevice",
            index=models.Index(
                fields=["company", "is_active"], name="biom_dev_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricdevice",
            index=models.Index(
                fields=["company", "sync_mode"], name="biom_dev_sync_mode_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricdevice",
            index=models.Index(fields=["company", "brand"], name="biom_dev_brand_idx"),
        ),
        migrations.AddConstraint(
            model_name="biometricdevice",
            constraint=models.UniqueConstraint(
                fields=("company", "device_code"), name="unique_device_code_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="biometricdevice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("serial_number__isnull", False)),
                fields=("company", "serial_number"),
                name="unique_active_serial_number_per_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancelocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("company", "name"),
                name="unique_active_location_name_per_company",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["company", "membership", "event_time"],
                name="att_evt_member_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["company", "event_time"], name="att_evt_company_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["company", "event_type"], name="att_evt_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceevent",
            index=models.Index(
                fields=["company", "attendance_method"], name="att_evt_method_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceaccessrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("company", "scope_type", "work_mode", "department"),
                name="unique_active_rule_combination",
            ),
        ),
    ]
