# Generated by Django 4.2.30 on 2026-06-22 13:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_membership_work_mode_and_more"),
        ("attendance", "0002_attendanceaccessrule_attendanceevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceaccessrule",
            name="validation_mode",
            field=models.CharField(
                choices=[
                    ("ALL", "All Configured Methods Required"),
                    ("ANY", "Any Configured Method Allowed"),
                ],
                default="ANY",
                max_length=15,
                verbose_name="Validation Mode",
            ),
        ),
        migrations.AlterField(
            model_name="companyattendancedefault",
            name="validation_mode",
            field=models.CharField(
                choices=[
                    ("ALL", "All Configured Methods Required"),
                    ("ANY", "Any Configured Method Allowed"),
                ],
                default="ANY",
                max_length=15,
                verbose_name="Validation Mode",
            ),
        ),
        migrations.AlterField(
            model_name="companyattendancemethod",
            name="method",
            field=models.CharField(
                choices=[
                    ("WEB", "Web/Mobile Dashboard Portal"),
                    ("GPS", "Geofenced Coordinate Boundary"),
                    ("FACE", "Biometric Facial Recognition Engine"),
                    ("BIOMETRIC", "Hardware Fingerprint Terminal"),
                    ("MANUAL", "Administrative Manual Overwrite"),
                    ("QR", "QR Code Scanning Framework"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Ingestion Channel Method Interface",
            ),
        ),
        migrations.AlterField(
            model_name="employeeattendanceoverride",
            name="validation_mode",
            field=models.CharField(
                choices=[
                    ("ALL", "All Configured Methods Required"),
                    ("ANY", "Any Configured Method Allowed"),
                ],
                default="ANY",
                max_length=15,
                verbose_name="Validation Mode",
            ),
        ),
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("FACE", "Face Verification"),
                            ("GPS", "GPS Verification"),
                            ("QR", "QR Code Verification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("verification_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("is_used", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to="companies.company",
                    ),
                ),
                (
                    "face_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to="attendance.faceenrollment",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to="attendance.attendancelocation",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to="companies.membership",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_verification_tokens",
                "indexes": [
                    models.Index(
                        fields=["company", "membership", "token_type", "is_used"],
                        name="attendance__company_55d570_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="attendance__expires_7dfbd4_idx"
                    ),
                ],
            },
        ),
    ]
