# Generated by Django 4.2.30 on 2026-06-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendanceaccessrule_validation_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faceenrollment",
            name="similarity_threshold",
            field=models.FloatField(
                default=0.93,
                verbose_name="Minimum Cosine Passing Vector Confidence Limit",
            ),
        ),
    ]
