# Generated by Django 4.2.30 on 2026-06-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_membership_work_mode_and_more"),
        ("attendance", "0004_alter_faceenrollment_similarity_threshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leave_year",
                    models.PositiveIntegerField(
                        help_text="The target operational accounting year this profile tracking applies to (e.g., 2026).",
                        verbose_name="Leave Year",
                    ),
                ),
                (
                    "allocated_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        help_text="Total base pool days available to this individual for the calendar year cycle.",
                        max_digits=5,
                        verbose_name="Allocated Days",
                    ),
                ),
                (
                    "used_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        help_text="Total sum count of approved utilized workflow leave days.",
                        max_digits=5,
                        verbose_name="Used Days",
                    ),
                ),
                (
                    "remaining_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        help_text="The actual net safe available entitlement days left to draw upon.",
                        max_digits=5,
                        verbose_name="Remaining Days",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Balance",
                "verbose_name_plural": "Leave Balances",
                "ordering": [
                    "-leave_year",
                    "membership__user__last_name",
                    "leave_type__name",
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="leaverequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="leavetype",
            options={
                "ordering": ["name"],
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
            },
        ),
        migrations.RenameIndex(
            model_name="leaverequest",
            new_name="idx_leavereq_company",
            old_name="attendance__company_0f15d0_idx",
        ),
        migrations.RenameIndex(
            model_name="leaverequest",
            new_name="idx_leavereq_membership",
            old_name="attendance__members_d91dc4_idx",
        ),
        migrations.RenameIndex(
            model_name="leaverequest",
            new_name="idx_leavereq_status",
            old_name="attendance__status_6e3dfd_idx",
        ),
        migrations.RenameIndex(
            model_name="leaverequest",
            new_name="idx_leavereq_start_date",
            old_name="attendance__start_d_89764a_idx",
        ),
        migrations.RenameIndex(
            model_name="leavetype",
            new_name="idx_leavetype_company",
            old_name="attendance__company_5143c3_idx",
        ),
        migrations.RenameIndex(
            model_name="leavetype",
            new_name="idx_leavetype_is_active",
            old_name="attendance__is_acti_61b8cc_idx",
        ),
        migrations.AlterUniqueTogether(
            name="leavetype",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Optional generic documentation or policy justification certificates uploaded by worker.",
                null=True,
                upload_to="leave_attachments/%Y/%m/",
                verbose_name="Evidence Document",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="half_day_session",
            field=models.CharField(
                blank=True,
                choices=[("first_half", "First Half"), ("second_half", "Second Half")],
                default="",
                help_text="Dictates partial day distribution segment details when is_half_day evaluates true.",
                max_length=20,
                verbose_name="Half Day Session Choice",
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="requires_attachment",
            field=models.BooleanField(
                default=False,
                help_text="Enables enforcement of document proofs or medical certificates on submission.",
                verbose_name="Requires Attachment",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="System clock tracking exact execution time of processing state approval mutations.",
                null=True,
                verbose_name="Approved Timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The authorized actor executing state lifecycle change controls.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leave_requests",
                to="companies.membership",
                verbose_name="Approver Membership Profile",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="company",
            field=models.ForeignKey(
                help_text="Multi-tenant context tracker isolating this transaction record.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(
                help_text="Inclusive final date bound of absent leave timeline tracking.",
                verbose_name="End Date",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="is_half_day",
            field=models.BooleanField(
                default=False,
                help_text="Flag designating if this event counts as a sub-day partial cycle block.",
                verbose_name="Is Half Day Request",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.ForeignKey(
                help_text="Protected baseline identity rules backing this registration data payload.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leave_requests",
                to="attendance.leavetype",
                verbose_name="Leave Type Rule",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="membership",
            field=models.ForeignKey(
                help_text="The worker seeking leave clearance visibility context.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="companies.membership",
                verbose_name="Employee Membership",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="reason",
            field=models.TextField(
                help_text="Explanatory text clarifying context for why the leave time is requested.",
                verbose_name="Reason Description",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Mandatory audit trail reason detail appended if status transitions to Rejected.",
                verbose_name="Rejection Context",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateField(
                help_text="First localized date of absent leave timeline tracking.",
                verbose_name="Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current processing tracking lifecycle flag state.",
                max_length=30,
                verbose_name="Workflow Status",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="total_days",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Calculated total decimal value balance impacted by this request.",
                max_digits=5,
                verbose_name="Total Accounted Days",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="allow_half_day",
            field=models.BooleanField(
                default=True,
                help_text="Enables employees to split individual work days when registering this type.",
                verbose_name="Allow Half-Day Requests",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="annual_quota",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Standard yearly baseline allotment of days granted for this policy.",
                verbose_name="Annual Quota",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="code",
            field=models.CharField(
                help_text="Unique shorthand token used for reporting and integrations (e.g., AL, SL).",
                max_length=20,
                verbose_name="Leave Type Code",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="company",
            field=models.ForeignKey(
                help_text="The tenant company owning this leave policy configuration.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_types",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed rules or context around this leave type policy.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Deactivating hides this choice from users without damaging historical data bindings.",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="is_paid",
            field=models.BooleanField(
                default=True,
                help_text="Designates if taking this leave type maintains normal payroll payout cycles.",
                verbose_name="Is Paid Leave",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="name",
            field=models.CharField(
                help_text="The display name of the leave type (e.g., Annual Leave, Sick Leave).",
                max_length=100,
                verbose_name="Leave Type Name",
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="requires_approval",
            field=models.BooleanField(
                default=True,
                help_text="Specifies if requests against this type must explicitly go through an approval cycle.",
                verbose_name="Requires Approval",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetype",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="uni_leavetype_company_code"
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="company",
            field=models.ForeignKey(
                help_text="The tenant workspace owning this specific balance ledger context.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_balances",
                to="companies.company",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="leave_type",
            field=models.ForeignKey(
                help_text="The specific leave type rule system defining these numbers.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leave_balances",
                to="attendance.leavetype",
                verbose_name="Leave Type Relation",
            ),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="membership",
            field=models.ForeignKey(
                help_text="The unique company member ledger profile context mapping this balance row.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_balances",
                to="companies.membership",
                verbose_name="Employee Membership",
            ),
        ),
        migrations.AddIndex(
            model_name="leavebalance",
            index=models.Index(fields=["company"], name="idx_leavebal_company"),
        ),
        migrations.AddIndex(
            model_name="leavebalance",
            index=models.Index(fields=["membership"], name="idx_leavebal_membership"),
        ),
        migrations.AddIndex(
            model_name="leavebalance",
            index=models.Index(fields=["leave_year"], name="idx_leavebal_year"),
        ),
        migrations.AddConstraint(
            model_name="leavebalance",
            constraint=models.UniqueConstraint(
                fields=("company", "membership", "leave_type", "leave_year"),
                name="uni_leavebal_mbr_type_year",
            ),
        ),
    ]
