# Generated by Django 4.2.30 on 2026-07-01 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_membership_work_mode_and_more"),
        ("attendance", "0005_leavebalance_alter_leaverequest_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRReportGenerationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_type", models.CharField(max_length=100)),
                ("filters_used", models.JSONField(default=dict)),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("CSV", "Comma Separated Values"),
                            ("EXCEL", "Microsoft Excel (.xlsx)"),
                            ("PDF", "Portable Document Format"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Execution"),
                            ("PROCESSING", "Processing Data Slices"),
                            ("COMPLETED", "Completed & Uploaded"),
                            ("FAILED", "Execution Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_histories",
                        to="companies.company",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to="companies.membership",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_report_generation_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HRReportAutomationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_type", models.CharField(max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Automated Run"),
                            ("WEEKLY", "Weekly Automated Run"),
                            ("MONTHLY", "Monthly Automated Run"),
                            ("QUARTERLY", "Quarterly Automated Run"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filters_template", models.JSONField(default=dict)),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("CSV", "Comma Separated Values"),
                            ("EXCEL", "Microsoft Excel (.xlsx)"),
                            ("PDF", "Portable Document Format"),
                        ],
                        default="CSV",
                        max_length=10,
                    ),
                ),
                (
                    "recipients_emails",
                    models.JSONField(
                        default=list, help_text="Target email notifications list."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to="companies.company",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schedules",
                        to="companies.membership",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_report_automation_schedules",
                "ordering": ["-created_at"],
            },
        ),
    ]
