# Generated by Django 4.2.30 on 2026-07-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_hrreportgenerationhistory_hrreportautomationschedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hrreportgenerationhistory",
            name="company",
        ),
        migrations.RemoveField(
            model_name="hrreportgenerationhistory",
            name="generated_by",
        ),
        migrations.DeleteModel(
            name="HRReportAutomationSchedule",
        ),
        migrations.DeleteModel(
            name="HRReportGenerationHistory",
        ),
    ]
