# Generated by Django 4.2.30 on 2026-05-20 02:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0006_department_conversation_department_head_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("agenda", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("department", "Department"),
                            ("project", "Project"),
                            ("interview", "Interview"),
                            ("training", "Training"),
                            ("townhall", "Townhall"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("scheduled", "Scheduled"),
                            ("recurring", "Recurring"),
                        ],
                        default="scheduled",
                        max_length=30,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("department", "Department"),
                            ("organization", "Organization"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                ("recurrence_rule", models.JSONField(blank=True, null=True)),
                ("max_participants", models.PositiveIntegerField(default=100)),
                ("waiting_room_enabled", models.BooleanField(default=False)),
                ("recording_enabled", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True)),
                (
                    "external_meeting_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_meetings",
                        to="companies.membership",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_meetings",
                        to="companies.membership",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True, related_name="meetings", to="companies.department"
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="MeetingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                        ],
                        default="waiting",
                        max_length=30,
                    ),
                ),
                (
                    "rtc_provider",
                    models.CharField(
                        choices=[
                            ("livekit", "LiveKit"),
                            ("agora", "Agora"),
                            ("jitsi", "Jitsi"),
                            ("daily", "Daily"),
                        ],
                        default="livekit",
                        max_length=30,
                    ),
                ),
                (
                    "rtc_room_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("peak_participant_count", models.PositiveIntegerField(default=0)),
                ("recording_enabled", models.BooleanField(default=False)),
                ("recording_url", models.URLField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ended_meeting_sessions",
                        to="companies.membership",
                    ),
                ),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_meeting_sessions",
                        to="companies.membership",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session_status"], name="meetings_me_session_c4570b_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="meetings_me_started_e1be02_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("co_host", "Co Host"),
                            ("participant", "Participant"),
                            ("viewer", "Viewer"),
                        ],
                        default="participant",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("joined", "Joined"),
                            ("left", "Left"),
                            ("no_show", "No Show"),
                        ],
                        default="invited",
                        max_length=30,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("attendance_duration_seconds", models.PositiveIntegerField(default=0)),
                ("joined_count", models.PositiveIntegerField(default=0)),
                ("is_present", models.BooleanField(default=False)),
                ("can_invite", models.BooleanField(default=False)),
                ("can_moderate", models.BooleanField(default=False)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_meeting_invitations",
                        to="companies.membership",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_participations",
                        to="companies.membership",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["meeting"], name="meetings_me_meeting_4eb3cd_idx"
                    ),
                    models.Index(
                        fields=["membership"], name="meetings_me_members_2dff56_idx"
                    ),
                    models.Index(
                        fields=["status"], name="meetings_me_status_d411b7_idx"
                    ),
                    models.Index(fields=["role"], name="meetings_me_role_10ee69_idx"),
                    models.Index(
                        fields=["is_present"], name="meetings_me_is_pres_60e7c4_idx"
                    ),
                ],
                "unique_together": {("meeting", "membership")},
            },
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["company"], name="meetings_me_company_f90203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["status"], name="meetings_me_status_14fbb6_idx"),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["visibility"], name="meetings_me_visibil_cfe46a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["category"], name="meetings_me_categor_cc20b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["schedule_type"], name="meetings_me_schedul_c8c5ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["scheduled_start"], name="meetings_me_schedul_852f94_idx"
            ),
        ),
    ]
