# Generated by Django 4.2.30 on 2026-05-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_department_conversation_department_head_and_more"),
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("department", "Department"),
                            ("project", "Project"),
                            ("team", "Team"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name="meeting",
            name="meetings_me_categor_cc20b5_idx",
        ),
        migrations.RemoveIndex(
            model_name="meeting",
            name="meetings_me_schedul_c8c5ae_idx",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="departments",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="agenda",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="cancel_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("interview", "Interview"),
                    ("training", "Training"),
                    ("townhall", "Townhall"),
                    ("project", "Project"),
                ],
                default="general",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("targeted", "Targeted"),
                    ("organization", "Organization"),
                    ("public", "Public"),
                ],
                default="private",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="meetingtarget",
            name="created_by_membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="companies.membership"
            ),
        ),
        migrations.AddField(
            model_name="meetingtarget",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="meetings.meeting",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingtarget",
            index=models.Index(
                fields=["meeting"], name="meetings_me_meeting_e6a702_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingtarget",
            index=models.Index(
                fields=["target_type"], name="meetings_me_target__79f314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingtarget",
            index=models.Index(
                fields=["target_id"], name="meetings_me_target__0591a1_idx"
            ),
        ),
    ]
