# Generated by Django 4.2.30 on 2026-05-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_meetingtarget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingsession",
            name="rtc_room_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="meetingsession",
            index=models.Index(
                fields=["rtc_provider"], name="meetings_me_rtc_pro_e00245_idx"
            ),
        ),
    ]
