# Generated by Django 4.2.30 on 2026-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_alter_meetingsession_rtc_room_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingparticipant",
            name="attendance_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="attendance_status",
            field=models.CharField(default="absent", max_length=30),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="last_joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
