# Generated by Django 4.2.30 on 2026-05-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_meetingparticipant_attendance_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="reminder_minutes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
