# Generated by Django 4.2.30 on 2026-07-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0007_membership_work_mode_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Concise title or summary of the task.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description, requirements, or instructions.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("in_review", "In Review"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="todo",
                        help_text="Current state of the task in the execution lifecycle.",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Urgency level of the task.",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Optional planned start date.", null=True
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional target deadline date.",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the task was marked completed.",
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="The employee membership currently assigned to execute this task.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="companies.membership",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The tenant company owning this task.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The employee membership who created this task.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tasks",
                        to="companies.membership",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional project association. If NULL, this is a Personal Task.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "db_table": "tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"], name="task_company_status_idx"
                    ),
                    models.Index(
                        fields=["company", "assigned_to", "status"],
                        name="task_company_assignee_idx",
                    ),
                    models.Index(
                        fields=["project", "status"], name="task_project_status_idx"
                    ),
                    models.Index(
                        fields=["company", "project", "created_by"],
                        name="task_personal_idx",
                    ),
                    models.Index(fields=["due_date"], name="task_due_date_idx"),
                ],
            },
        ),
    ]
