# Generated by Django 4.2.29 on 2026-04-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_department_description_alter_department_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
