# Generated by Django 4.2.30 on 2026-05-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_remove_conversation_department_and_more"),
        ("companies", "0005_membership_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="conversation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_department",
                to="chat.conversation",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="companies.membership",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="companies.department",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("company", "name")},
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["slug"], name="companies_c_slug_45751b_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["status"], name="companies_c_status_2407e4_idx"),
        ),
        migrations.AddIndex(
            model_name="companyinvite",
            index=models.Index(
                fields=["company"], name="companies_c_company_6bbca1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyinvite",
            index=models.Index(fields=["email"], name="companies_c_email_bedd53_idx"),
        ),
        migrations.AddIndex(
            model_name="companyinvite",
            index=models.Index(
                fields=["token_id"], name="companies_c_token_i_87d0df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyinvite",
            index=models.Index(
                fields=["expires_at"], name="companies_c_expires_1a70df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["company"], name="companies_d_company_c31b1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["parent"], name="companies_d_parent__ca2ed0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["head"], name="companies_d_head_id_ab354c_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["company"], name="companies_m_company_45a5f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["department"], name="companies_m_departm_4216ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["is_active"], name="companies_m_is_acti_0552eb_idx"
            ),
        ),
    ]
