# Generated by Django 4.2.30 on 2026-06-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_department_conversation_department_head_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("office", "Office"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("field", "Field"),
                ],
                default="office",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["work_mode"], name="companies_m_work_mo_ad0f1f_idx"
            ),
        ),
    ]
