# Generated by Django 4.2.29 on 2026-03-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_platform", "0002_remove_platformrole_permissions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlatformPermission",
        ),
    ]
