# Generated by Django 4.2.29 on 2026-03-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0002_permission_scope"),
        ("core_platform", "0003_delete_platformpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformrole",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="platform_roles", to="rbac.permission"
            ),
        ),
    ]
