# Generated by Django 4.2.30 on 2026-05-09 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0005_membership_last_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("sound_enabled", models.BooleanField(default=True)),
                ("chat_message_enabled", models.BooleanField(default=True)),
                ("mention_enabled", models.BooleanField(default=True)),
                ("meeting_enabled", models.BooleanField(default=True)),
                ("attendance_enabled", models.BooleanField(default=True)),
                ("system_enabled", models.BooleanField(default=True)),
                (
                    "membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="companies.membership",
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("mention", "Mention"),
                            ("system", "System"),
                            ("meeting", "Meeting"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="companies.membership",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDevice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_id", models.CharField(max_length=255)),
                ("token", models.TextField()),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("android", "Android"),
                            ("ios", "iOS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_devices",
                        to="companies.membership",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_devices",
                "indexes": [
                    models.Index(
                        fields=["membership"], name="notificatio_members_5e792e_idx"
                    ),
                    models.Index(
                        fields=["user"], name="notificatio_user_id_4ae68e_idx"
                    ),
                    models.Index(
                        fields=["device_id"], name="notificatio_device__735f95_idx"
                    ),
                    models.Index(
                        fields=["platform"], name="notificatio_platfor_e14b42_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="notificatio_is_acti_bb2bc1_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_43c447_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="notificationdevice",
            constraint=models.UniqueConstraint(
                fields=("membership", "device_id"), name="unique_membership_device"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["membership"], name="notificatio_members_261ae6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["type"], name="notificatio_type_8a8a78_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["is_read"], name="notificatio_is_read_3f8c44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_e4c995_idx"
            ),
        ),
    ]
