# Generated by Django 4.2.30 on 2026-05-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notificationdevice",
            name="notificatio_device__735f95_idx",
        ),
        migrations.AlterField(
            model_name="notificationdevice",
            name="token",
            field=models.TextField(unique=True),
        ),
    ]
