# Generated by Django 4.2.30 on 2026-05-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_remove_notificationdevice_notificatio_device__735f95_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationdevice",
            name="token",
            field=models.TextField(),
        ),
    ]
