# Generated by Django 4.2.30 on 2026-05-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notificationdevice_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="email_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
