# Generated by Django 4.2.30 on 2026-05-31 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0006_department_conversation_department_head_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("payroll", "Payroll"),
                            ("attendance", "Attendance"),
                            ("project", "Project"),
                            ("task", "Task"),
                            ("invoice", "Invoice"),
                            ("subscription", "Subscription"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField()),
                ("remind_at", models.DateTimeField()),
                ("minutes_before", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="companies.company",
                    ),
                ),
                (
                    "recipient_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="companies.membership",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="reminders_r_status_c60465_idx"
                    ),
                    models.Index(
                        fields=["remind_at"], name="reminders_r_remind__435da1_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="reminders_r_target__54e1fd_idx",
                    ),
                    models.Index(
                        fields=["recipient_membership"],
                        name="reminders_r_recipie_74a0da_idx",
                    ),
                    models.Index(
                        fields=["status", "remind_at"],
                        name="reminders_r_status_066074_idx",
                    ),
                ],
            },
        ),
    ]
