# Generated by Django 4.2.29 on 2026-03-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_message_chat_messag_convers_d0740f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("read", "Read"),
                ],
                default="sent",
                max_length=20,
            ),
        ),
    ]
