# Generated by Django 4.2.29 on 2026-03-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_department_description_alter_department_parent_and_more"),
        ("chat", "0003_message_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="messageread",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="messageread",
            name="membership",
        ),
        migrations.RemoveField(
            model_name="messageread",
            name="message",
        ),
        migrations.RemoveField(
            model_name="message",
            name="status",
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["updated_at"], name="chat_conver_updated_09e193_idx"
            ),
        ),
        migrations.DeleteModel(
            name="MessageRead",
        ),
        migrations.AddField(
            model_name="messagestatus",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.membership"
            ),
        ),
        migrations.AddField(
            model_name="messagestatus",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="chat.message",
            ),
        ),
        migrations.AddIndex(
            model_name="messagestatus",
            index=models.Index(
                fields=["message", "membership"], name="chat_messag_message_535490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagestatus",
            index=models.Index(
                fields=["membership", "status"], name="chat_messag_members_cc36df_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagestatus",
            unique_together={("message", "membership")},
        ),
    ]
