# Generated by Django 4.2.29 on 2026-04-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_messagestatus_alter_messageread_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationparticipant",
            name="unread_count",
            field=models.IntegerField(default=0),
        ),
    ]
