# Generated by Django 4.2.30 on 2026-05-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_message_reply_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="file",
        ),
        migrations.AddField(
            model_name="message",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("file", "File"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
