# Generated by Django 4.2.30 on 2026-05-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_remove_message_file_message_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
