# Generated by Django 4.2.30 on 2026-05-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_message_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
