# Generated by Django 4.2.30 on 2026-05-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_membership_last_seen"),
        ("chat", "0010_conversation_avatar_conversation_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="message",
            name="system_event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("group_created", "Group Created"),
                    ("member_added", "Member Added"),
                    ("member_removed", "Member Removed"),
                    ("member_left", "Member Left"),
                    ("role_updated", "Role Updated"),
                    ("group_updated", "Group Updated"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("file", "File"),
                    ("system", "System"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="companies.membership",
            ),
        ),
    ]
