# Generated by Django 4.2.28 on 2026-02-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyinvite'),
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token_type',
            field=models.CharField(choices=[('EMAIL_VERIFY', 'Email Verify'), ('PASSWORD_RESET', 'Password Reset'), ('INVITE', 'Invite'), ('TWO_FACTOR', 'Two Factor')], max_length=20),
        ),
    ]
