# Generated by Django 4.2.28 on 2026-02-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('trial_days', models.IntegerField(default=0)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('max_projects', models.IntegerField(blank=True, null=True)),
                ('max_chats', models.IntegerField(blank=True, null=True)),
                ('ai_credits_per_month', models.IntegerField(default=0)),
                ('max_storage_gb', models.IntegerField(default=5)),
                ('automation_enabled', models.BooleanField(default=False)),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('custom_branding', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('api_access', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('pending_payment', 'Pending Payment')], max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(max_length=50)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
