# Generated by Django 4.2.28 on 2026-02-25 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_chats',
        ),
        migrations.AddField(
            model_name='plan',
            name='custom_roles_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_departments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ai_credits_per_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_projects',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_storage_gb',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
