# Generated by Django 4.2.28 on 2026-03-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_plan_max_chats_plan_custom_roles_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
