# Generated by Django 4.2.30 on 2026-06-06 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0006_department_conversation_department_head_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("outlook", "Outlook")],
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_accounts",
                        to="companies.membership",
                    ),
                ),
            ],
            options={
                "unique_together": {("membership", "provider")},
            },
        ),
    ]
