# Generated by Django 4.2.30 on 2026-06-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calendaraccount",
            old_name="is_active",
            new_name="is_connected",
        ),
        migrations.AddField(
            model_name="calendaraccount",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendaraccount",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="calendaraccount",
            name="provider_account_id",
            field=models.CharField(db_index=True, default="temp", max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="calendaraccount",
            index=models.Index(
                fields=["membership"], name="calendars_c_members_ddbdf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendaraccount",
            index=models.Index(
                fields=["provider"], name="calendars_c_provide_513290_idx"
            ),
        ),
    ]
