# Generated by Django 4.2.30 on 2026-06-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("calendars", "0002_rename_is_active_calendaraccount_is_connected_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEventSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=30)),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "external_event_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "external_calendar_id",
                    models.CharField(default="primary", max_length=255),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "calendar_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_syncs",
                        to="calendars.calendaraccount",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["calendar_account"],
                        name="calendars_c_calenda_91488d_idx",
                    ),
                    models.Index(
                        fields=["provider"], name="calendars_c_provide_7bfe82_idx"
                    ),
                    models.Index(
                        fields=["sync_status"], name="calendars_c_sync_st_05b3ad_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="calendars_c_content_f9b4e5_idx",
                    ),
                    models.Index(
                        fields=["external_event_id"],
                        name="calendars_c_externa_b26994_idx",
                    ),
                ],
                "unique_together": {
                    ("calendar_account", "content_type", "object_id"),
                    ("calendar_account", "provider", "external_event_id"),
                },
            },
        ),
    ]
