# Generated by Django 4.2.29 on 2026-03-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="scope",
            field=models.CharField(
                choices=[("platform", "Platform"), ("tenant", "Tenant")],
                default="tenant",
                max_length=20,
            ),
        ),
    ]
