"""
CSV Export Service

Generates attendance report exports in CSV format using Python's built-in
csv module. All generation happens in-memory via io.BytesIO.

No temporary files. No external dependencies beyond the Python standard library.
"""

import csv
import io
from typing import Any

from apps.companies.models import Company


class CSVExportService:
    """
    CSV file generator for attendance reports.

    Produces a UTF-8 encoded CSV with BOM for Excel compatibility,
    containing all employee rows and a trailing summary block.
    """

    # Column headers matching the annotated fields from AttendanceReportSelector.
    EMPLOYEE_HEADERS: list[str] = [
        "Employee Name",
        "Department",
        "Job Title",
        "Present Days",
        "Absent Days",
        "Leave Days",
        "Holiday Days",
        "Weekend Days",
        "Late Count",
        "Needs Review",
        "Attendance %",
        "Total Work Hours",
        "Overtime Hours",
    ]

    @classmethod
    def generate(
        cls,
        *,
        dataset: list[Any],
        summary: dict[str, Any],
        filter_metadata: dict[str, Any],
        company: Company,
    ) -> io.BytesIO:
        """
        Generate a CSV file in memory and return a BytesIO buffer.

        CRITICAL FIX: We build the CSV in a StringIO first, then encode to
        BytesIO. We do NOT use TextIOWrapper wrapping BytesIO because
        TextIOWrapper closes the underlying BytesIO buffer when it goes
        out of scope, causing "I/O operation on closed file" downstream.
        """
        # ------------------------------------------------------------------
        # Build CSV content in StringIO first (no buffer-closing issues)
        # ------------------------------------------------------------------
        string_buffer = io.StringIO(newline="")
        writer = csv.writer(string_buffer)

        # ------------------------------------------------------------------
        # 1. Report Metadata Header
        # ------------------------------------------------------------------
        writer.writerow(["Attendance Report"])
        writer.writerow(["Company", company.name])

        generated_by = filter_metadata.get("generated_by", "")
        if generated_by:
            writer.writerow(["Generated By", generated_by])

        generated_at = filter_metadata.get("generated_at", "")
        if generated_at:
            writer.writerow(["Generated At", generated_at])

        writer.writerow([
            "Reporting Period",
            f"{filter_metadata.get('date_from', 'N/A')} to {filter_metadata.get('date_to', 'N/A')}",
        ])
        writer.writerow([])  # Blank row

        # ------------------------------------------------------------------
        # 2. Applied Filters
        # ------------------------------------------------------------------
        writer.writerow(["Applied Filters"])
        filter_items = [
            ("Month", filter_metadata.get("selected_month") or "All"),
            ("Year", filter_metadata.get("selected_year") or "All"),
            ("Department", filter_metadata.get("selected_department") or "All"),
        ]
        for label, value in filter_items:
            if value is not None:
                writer.writerow([label, str(value)])
        writer.writerow([])

        # ------------------------------------------------------------------
        # 3. Employee Data Table
        # ------------------------------------------------------------------
        writer.writerow(cls.EMPLOYEE_HEADERS)

        for row in dataset:
            writer.writerow(cls._extract_employee_row(row))

        writer.writerow([])

        # ------------------------------------------------------------------
        # 4. Summary Block
        # ------------------------------------------------------------------
        writer.writerow(["Summary"])
        writer.writerow([])
        for key, value in summary.items():
            writer.writerow(["", key.replace("_", " ").title(), value])

        # ------------------------------------------------------------------
        # 5. Encode StringIO content to BytesIO with UTF-8 BOM
        # ------------------------------------------------------------------
        csv_string = string_buffer.getvalue()
        string_buffer.close()

        buffer = io.BytesIO()
        buffer.write(b"\xef\xbb\xbf")  # UTF-8 BOM for Excel
        buffer.write(csv_string.encode("utf-8-sig"))
        buffer.seek(0)

        return buffer

    @classmethod
    def _extract_employee_row(cls, row: Any) -> list[Any]:
        """
        Extract scalar values from an annotated Membership object into
        a flat list matching EMPLOYEE_HEADERS.
        """
        user = row.user
        department = row.department

        return [
            f"{user.first_name} {user.last_name}".strip() or user.username or "N/A",
            department.name if department else "N/A",
            row.job_title or "N/A",
            row.present_days,
            row.absent_days,
            row.leave_days,
            row.holiday_days,
            row.weekend_days,
            row.late_count,
            "Yes" if row.needs_review else "No",
            row.attendance_percentage,
            row.total_work_hours,
            row.overtime_hours,
        ]