"""
Excel Export Service

Generates professional .xlsx attendance report workbooks using openpyxl.
All generation happens in-memory. No temporary files.

Features:
    - Company header with optional logo
    - Centered report title
    - Generated By / Generated At
    - Reporting Period
    - Applied filters section
    - Summary cards (KPI section)
    - Employee data table with auto column widths
    - Bold headers, freeze first row
    - Number and percentage formatting
    - Professional borders and alignment
    - Consistent spacing
"""

import io
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import (
    Font,
    Alignment,
    Border,
    Side,
    PatternFill,
)
from openpyxl.utils import get_column_letter
from openpyxl.drawing.image import Image as XLImage

from apps.companies.models import Company


class ExcelExportService:
    """
    Excel (.xlsx) file generator for attendance reports.

    Produces a single-sheet workbook with professional formatting
    suitable for HR review and executive distribution.
    """

    # Color palette (enterprise theme)
    PRIMARY_COLOR = "1F4E79"
    HEADER_FONT_COLOR = "FFFFFF"
    TITLE_FONT_COLOR = "1F4E79"
    ALT_ROW_FILL = "F2F2F2"
    SUMMARY_FILL = "E7E6E6"
    BORDER_COLOR = "B4B4B4"
    DARK_GRAY = "404040"

    # Column definitions: (header, attribute_path, width, format)
    # format: None | "number" | "percentage" | "decimal2"
    COLUMNS: list[tuple[str, str, int, str | None]] = [
        ("Employee Name", "user.get_full_name", 28, None),
        ("Department", "department.name", 22, None),
        ("Job Title", "job_title", 20, None),
        ("Present Days", "present_days", 14, "number"),
        ("Absent Days", "absent_days", 14, "number"),
        ("Leave Days", "leave_days", 14, "number"),
        ("Holiday Days", "holiday_days", 14, "number"),
        ("Weekend Days", "weekend_days", 14, "number"),
        ("Late Count", "late_count", 12, "number"),
        ("Needs Review", "needs_review", 14, None),
        ("Attendance %", "attendance_percentage", 14, "percentage"),
        ("Total Work Hours", "total_work_hours", 16, "decimal2"),
        ("Overtime Hours", "overtime_hours", 16, "decimal2"),
    ]

    @classmethod
    def generate(
        cls,
        *,
        dataset: list[Any],
        summary: dict[str, Any],
        filter_metadata: dict[str, Any],
        company: Company,
    ) -> io.BytesIO:
        """
        Generate a professional .xlsx workbook in memory.

        Args:
            dataset: List of annotated Membership objects.
            summary: Dictionary of global summary metrics.
            filter_metadata: Dictionary describing applied filters and generation context.
            company: Tenant Company for branding.

        Returns:
            io.BytesIO buffer containing the workbook.
        """
        wb = Workbook()
        ws = wb.active
        ws.title = "Attendance Report"

        # ------------------------------------------------------------------
        # Pre-define reusable styles
        # ------------------------------------------------------------------
        thin_border = Border(
            left=Side(style="thin", color=cls.BORDER_COLOR),
            right=Side(style="thin", color=cls.BORDER_COLOR),
            top=Side(style="thin", color=cls.BORDER_COLOR),
            bottom=Side(style="thin", color=cls.BORDER_COLOR),
        )

        header_font = Font(bold=True, color=cls.HEADER_FONT_COLOR, size=11)
        header_fill = PatternFill(
            start_color=cls.PRIMARY_COLOR,
            end_color=cls.PRIMARY_COLOR,
            fill_type="solid",
        )
        header_alignment = Alignment(
            horizontal="center", vertical="center", wrap_text=True
        )

        title_font = Font(bold=True, size=18, color=cls.TITLE_FONT_COLOR)
        title_alignment = Alignment(horizontal="center", vertical="center")

        subtitle_font = Font(bold=True, size=11, color=cls.TITLE_FONT_COLOR)
        normal_font = Font(size=10)
        normal_alignment = Alignment(horizontal="left", vertical="center")
        center_alignment = Alignment(horizontal="center", vertical="center")
        right_alignment = Alignment(horizontal="right", vertical="center")

        summary_label_font = Font(bold=True, size=10, color=cls.TITLE_FONT_COLOR)
        summary_value_font = Font(bold=True, size=12, color=cls.PRIMARY_COLOR)
        summary_fill = PatternFill(
            start_color=cls.SUMMARY_FILL,
            end_color=cls.SUMMARY_FILL,
            fill_type="solid",
        )

        num_fmt_int = "0"
        num_fmt_pct = "0.00%"
        num_fmt_dec2 = "0.00"

        current_row = 1

        # ------------------------------------------------------------------
        # 1. Company Logo (optional)
        # ------------------------------------------------------------------
        if company.logo and hasattr(company.logo, "path"):
            try:
                img = XLImage(company.logo.path)
                # Scale logo to reasonable size (max ~120px width)
                max_width = 120
                if img.width > max_width:
                    ratio = max_width / img.width
                    img.width = max_width
                    img.height = int(img.height * ratio)
                ws.add_image(img, f"A{current_row}")
                current_row += 5  # Leave space for logo
            except Exception:
                # Skip logo if any error occurs. Never fail.
                pass

        # ------------------------------------------------------------------
        # 2. Company Name & Report Title
        # ------------------------------------------------------------------
        ws.merge_cells(
            start_row=current_row,
            start_column=1,
            end_row=current_row,
            end_column=len(cls.COLUMNS),
        )
        cell = ws.cell(row=current_row, column=1, value=company.name)
        cell.font = Font(bold=True, size=14, color=cls.PRIMARY_COLOR)
        cell.alignment = Alignment(horizontal="left", vertical="center")
        current_row += 1

        ws.merge_cells(
            start_row=current_row,
            start_column=1,
            end_row=current_row,
            end_column=len(cls.COLUMNS),
        )
        cell = ws.cell(row=current_row, column=1, value="Attendance Report")
        cell.font = title_font
        cell.alignment = title_alignment
        current_row += 1

        # ------------------------------------------------------------------
        # 3. Generation Metadata
        # ------------------------------------------------------------------
        generated_by = filter_metadata.get("generated_by", "")
        generated_at = filter_metadata.get("generated_at", "")

        meta_items = []
        if generated_by:
            meta_items.append(("Generated By", generated_by))
        if generated_at:
            meta_items.append(("Generated At", generated_at))

        meta_items.append(
            (
                "Reporting Period",
                f"{filter_metadata.get('date_from', 'N/A')} to {filter_metadata.get('date_to', 'N/A')}",
            )
        )

        for label, value in meta_items:
            ws.merge_cells(
                start_row=current_row,
                start_column=1,
                end_row=current_row,
                end_column=len(cls.COLUMNS),
            )
            cell = ws.cell(row=current_row, column=1, value=f"{label}: {value}")
            cell.font = Font(italic=True, size=9, color=cls.DARK_GRAY)
            cell.alignment = Alignment(horizontal="center", vertical="center")
            current_row += 1

        current_row += 1  # Blank row

        # ------------------------------------------------------------------
        # 4. Applied Filters Section
        # ------------------------------------------------------------------
        ws.merge_cells(
            start_row=current_row,
            start_column=1,
            end_row=current_row,
            end_column=2,
        )
        cell = ws.cell(row=current_row, column=1, value="Applied Filters")
        cell.font = subtitle_font
        current_row += 1

        filter_items = [
            ("Month", filter_metadata.get("selected_month") or "All"),
            ("Year", filter_metadata.get("selected_year") or "All"),
            ("Department", filter_metadata.get("selected_department") or "All"),
        ]
        for label, value in filter_items:
            ws.cell(row=current_row, column=1, value=label).font = Font(
                bold=True, size=10
            )
            ws.cell(row=current_row, column=2, value=str(value)).font = normal_font
            current_row += 1
        current_row += 1  # Blank row

        # ------------------------------------------------------------------
        # 5. Summary Cards (KPI Section)
        # ------------------------------------------------------------------
        ws.merge_cells(
            start_row=current_row,
            start_column=1,
            end_row=current_row,
            end_column=len(cls.COLUMNS),
        )
        cell = ws.cell(row=current_row, column=1, value="Summary")
        cell.font = subtitle_font
        current_row += 1

        summary_items = [
            ("Total Employees", summary.get("total_employees", 0)),
            ("Present", summary.get("present_employees", 0)),
            ("Absent", summary.get("absent_employees", 0)),
            ("On Leave", summary.get("employees_on_leave", 0)),
            ("Late Arrivals", summary.get("employees_late", 0)),
            ("Avg Attendance %", summary.get("average_attendance_percentage", 0)),
            ("Total Work Hours", summary.get("total_work_hours", 0)),
            ("Total OT Hours", summary.get("total_overtime_hours", 0)),
        ]

        # Render summary cards in a 4-column grid (2 cards per row)
        cards_per_row = 4
        for i in range(0, len(summary_items), cards_per_row):
            row = summary_items[i : i + cards_per_row]
            for col_offset, (label, value) in enumerate(row):
                base_col = col_offset * 2 + 1
                # Label
                label_cell = ws.cell(row=current_row, column=base_col, value=label)
                label_cell.font = summary_label_font
                label_cell.fill = summary_fill
                label_cell.alignment = center_alignment
                label_cell.border = thin_border
                # Value
                value_cell = ws.cell(row=current_row, column=base_col + 1, value=value)
                value_cell.font = summary_value_font
                value_cell.fill = summary_fill
                value_cell.alignment = center_alignment
                value_cell.border = thin_border
            current_row += 1
        current_row += 1  # Blank row

        # ------------------------------------------------------------------
        # 6. Employee Data Table
        # ------------------------------------------------------------------
        ws.merge_cells(
            start_row=current_row,
            start_column=1,
            end_row=current_row,
            end_column=len(cls.COLUMNS),
        )
        cell = ws.cell(row=current_row, column=1, value="Employee Details")
        cell.font = subtitle_font
        current_row += 1

        # Header row
        for col_idx, (header, _, width, _) in enumerate(cls.COLUMNS, start=1):
            cell = ws.cell(row=current_row, column=col_idx, value=header)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = header_alignment
            cell.border = thin_border
            ws.column_dimensions[get_column_letter(col_idx)].width = width

        header_row = current_row
        current_row += 1

        # Data rows
        for idx, row_obj in enumerate(dataset):
            for col_idx, (_, attr_path, _, fmt) in enumerate(cls.COLUMNS, start=1):
                value = cls._resolve_attribute(row_obj, attr_path)
                cell = ws.cell(row=current_row, column=col_idx, value=value)
                cell.font = normal_font

                # Alignment
                if col_idx <= 3:
                    cell.alignment = normal_alignment
                else:
                    cell.alignment = center_alignment

                # Number formatting
                if fmt == "number":
                    cell.number_format = num_fmt_int
                elif fmt == "percentage":
                    cell.number_format = num_fmt_pct
                elif fmt == "decimal2":
                    cell.number_format = num_fmt_dec2

                cell.border = thin_border

                # Alternating row fill
                if idx % 2 == 1:
                    cell.fill = PatternFill(
                        start_color=cls.ALT_ROW_FILL,
                        end_color=cls.ALT_ROW_FILL,
                        fill_type="solid",
                    )
            current_row += 1

        # ------------------------------------------------------------------
        # 7. Final formatting
        # ------------------------------------------------------------------
        # Freeze the header row (freeze below the data table header)
        ws.freeze_panes = f"A{header_row + 1}"

        # Auto-adjust row heights for header
        ws.row_dimensions[header_row].height = 22

        # ------------------------------------------------------------------
        # 8. Write to buffer
        # ------------------------------------------------------------------
        buffer = io.BytesIO()
        wb.save(buffer)
        buffer.seek(0)

        return buffer

    @classmethod
    def _resolve_attribute(cls, obj: Any, attr_path: str) -> Any:
        """
        Resolve a dotted attribute path against an object.

        Supports simple attribute access and common computed properties.
        Special cases:
            - "user.get_full_name" -> f"{first_name} {last_name}"
            - "needs_review" -> "Yes" / "No"

        Args:
            obj: The annotated Membership instance.
            attr_path: Dot-notation path (e.g., "user.first_name", "present_days").

        Returns:
            The resolved scalar value.
        """
        if attr_path == "user.get_full_name":
            user = obj.user
            name = f"{user.first_name or ''} {user.last_name or ''}".strip()
            return name or user.username or "N/A"

        if attr_path == "department.name":
            dept = obj.department
            return dept.name if dept else "N/A"

        if attr_path == "needs_review":
            return "Yes" if obj.needs_review else "No"

        # Standard attribute resolution
        parts = attr_path.split(".")
        value = obj
        for part in parts:
            value = getattr(value, part, None)
            if value is None:
                return "N/A"
        return value