# Generated by Django 4.2.30 on 2026-07-21 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0007_membership_work_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the project.", max_length=255
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique identifier within the company (e.g., PROJ-001).",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the project scope and goals.",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        help_text="Public: any employee with view permission can access. Private: only explicit members can access.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="planning",
                        help_text="Current lifecycle state of the project.",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Planned or actual start date.", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Planned or actual end date.", null=True
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the project was archived. Set automatically when status transitions to Archived.",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366F1",
                        help_text="Hex color for visual identification (e.g., #FF5733).",
                        max_length=7,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact person at the client organization.",
                        max_length=255,
                    ),
                ),
                (
                    "client_company",
                    models.CharField(
                        blank=True,
                        help_text="Name of the external client company.",
                        max_length=255,
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the client contact.",
                        max_length=254,
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the client contact.",
                        max_length=30,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company this project belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The employee who created this project.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_created",
                        to="companies.membership",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The employee responsible for this project.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_projects",
                        to="companies.membership",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The employee who last modified this project.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_updated",
                        to="companies.membership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("member", "Member"),
                        ],
                        default="member",
                        help_text="Project-level authority: Owner, Manager, or Member.",
                        max_length=20,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the member was added to the project.",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Optional context for this membership (e.g., role description).",
                        max_length=255,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The employee who invited or added this member.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_members_added",
                        to="companies.membership",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        help_text="The employee participating in the project.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to="companies.membership",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The project this membership belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Member",
                "verbose_name_plural": "Project Members",
                "db_table": "project_members",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(fields=["project", "role"], name="project_role_idx"),
                    models.Index(
                        fields=["membership", "project"], name="membership_project_idx"
                    ),
                    models.Index(fields=["role"], name="role_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "owner")),
                fields=("project",),
                name="single_owner_per_project",
                violation_error_message="A project can have only one Owner.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together={("project", "membership")},
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["company", "status"], name="company_status_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["company", "visibility"], name="company_visibility_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["company", "owner"], name="company_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["company", "archived_at"], name="company_archived_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="status_idx"),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("start_date__isnull", True),
                    ("end_date__isnull", True),
                    ("start_date__lte", models.F("end_date")),
                    _connector="OR",
                ),
                name="check_start_before_end",
                violation_error_message="End date must be on or after start date.",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(("color__regex", "^#[0-9A-Fa-f]{6}$")),
                name="check_valid_hex_color",
                violation_error_message="Color must be a valid 6-digit hex code (e.g., #6366F1).",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "archived"), _negated=True),
                    ("archived_at__isnull", False),
                    _connector="OR",
                ),
                name="check_archived_has_timestamp",
                violation_error_message="Archived projects must have an archived_at timestamp.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("company", "code")},
        ),
    ]
